import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
    Dashboard header
     {children}
      </body>
    </html>
  );
}
