import type { Metadata } from 'next';
import '../globals.css';
import { Container, Header } from '@/shared';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Next Pizza| Главная ',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense>
          <Header
            hasSearch={false}
            hasCart={false}
            className="border-b-gray-200"
          />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
